# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_legs', models.IntegerField()),
                ('pl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_gain', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
