# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='net_gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
