# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-20 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
        ('legs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='positions.Position'),
            preserve_default=False,
        ),
    ]
